[toolchain]
anchor_version = "0.29.0"
solana_version = "2.0.24"

[features]
seeds = false
skip-lint = false

[programs.localnet]
excelsior = "CihitmkdTdh48gvUZSjU7rZ8EARQksJNxspwnRu7ZhAp"

[programs.devnet]
excelsior = "CihitmkdTdh48gvUZSjU7rZ8EARQksJNxspwnRu7ZhAp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallets/admin.json"
priority_fee = 0

[scripts]
test = "bash scripts/test_runner.sh"
create-tokens = "npx ts-node scripts/create_tokens.ts"
init-dist = "npx ts-node scripts/init_distribution.ts"

[build]
verifiable = false
